### ISSUE TITLE
NullPointerException if no logger

### ISSUE THREAD

**Issue by darylteo** [stephanenicolas/afterburner#2]
Remove the hard dependency on Logger instance if not provided (or spawn a basic one in AfterBurner.java)

**Comment by stephanenicolas** [comment]
Thx I will look into it this week.

@darylteo, could you have a look at building the sample with your gradle plugin ?

**Comment by darylteo** [comment]
I did. I got a Parse error (missing semicolon) the last I looked.

**Comment by stephanenicolas** [comment]
The system changed. I now use SLF4j (via lombok) and it's compatible with gradle logging system.
